### ISSUE TITLE
unsupported address encoding(56) of personality function in CIE for architecture arm64

### ISSUE THREAD

**Issue by jimmymjing** [DigitalStrawberry/ANE-Bugsee#1]
Hello, I'm getting the error "unsupported address encoding(56) of personality function in CIE for architecture arm64" when I try to compile the ipa. I'm using Air 31 with adhoc provisioning profile. Thanks for your help.

**Comment by ecornbower** [comment]
@jimmymjing Thanks for reporting this. Our main developer for the repo is out this week on vacation but he'll take a look into it next week. Thanks for your patience!

**Comment by marpies** [comment]
Hi @jimmymjing,

Are you trying to package your app on Windows? I've only seen this error on Windows and unfortunately I'm not aware of any fix for this.

**Comment by jimmymjing** [comment]
Hi, I forgot to mention that I’m compiling the app on Windows... I will just wait a bit to see if there could be a fix in the future. Thanks so much!
