### ISSUE TITLE
stripping of extra data during build to prevent submission rejection

### ISSUE THREAD

**Issue by jimmymjing** [DigitalStrawberry/ANE-Bugsee#2]
Hi, I have read the line from Bugsee's integration guide saying "stripping of extra data during build to prevent submission rejection". 
If I need to use bugsee in my released build, do I have to do any extra settings? Thanks.

**Comment by marpies** [comment]
The ANE currently uses Bugsee v1.19 so according to the documentation you shouldn't worry about the additional build steps for now.

**Comment by jimmymjing** [comment]
Thanks! One more question... 
I read the doc at Bugsee which asks to config "Auto dSYM upload". How are we going to do it in Air (or do we need to)? Thanks!

**Comment by marpies** [comment]
The dSYM file is generated when you create your IPA (on macOS at least). You will need to create a script yourself or tweak the one provided by Bugsee to have the file uploaded automatically. However from our experience the symbolicated crashes for AIR apps are not very useful anyway.

Alternatively you could add an error's stack trace manually in the `logError` call like this:

```as3
Bugsee.instance.logError("error", 123, { stackTrace: new Error().getStackTrace() });
```
