### ISSUE TITLE
Feedback controller & notification

### ISSUE THREAD

**Issue by jimmymjing** [DigitalStrawberry/ANE-Bugsee#3]
Hi,
The doc says "Bugsee implements built in single threaded messenger to allow your users to communicate with your support and developers".
Are we able to achieve this as well? It would be really cool to enable in-game communication.

**Comment by marpies** [comment]
We have added new APIs in the [latest release](https://github.com/DigitalStrawberry/ANE-Bugsee/releases/tag/v1.0.2):

```as3
Bugsee.instance.setDefaultFeedbackGreeting("greeting");
Bugsee.instance.showFeedbackController();
```

Note we have noticed an occasional crash when opening the feedback controller so it looks like there may be a bug in the Bugsee SDK.

You can add an event listener to receive feedback messages coming from the server, but it seems the messages are only received during initialization and not during a live chat session:

```as3
Bugsee.instance.addEventListener(BugseeEvent.FEEDBACK, feedbackReceived);
Bugsee.instance.init(...);

...

private function feedbackReceived(event:BugseeEvent):void
{
	trace(event.messages);
}
```
