### ISSUE TITLE
update to the latest version

### ISSUE THREAD

**Issue by jimmymjing** [DigitalStrawberry/ANE-Bugsee#4]
Hello, I see that BugSee ANE hasn't been updated over a year. Would you please kindly update it to the latest( latests SDK releases for iOS (1.24.0), Android (1.15.0) )? Thanks so much.
p.s. I'm currently using quite a few of your ANEs including Amplitude. It would be awesome if you could help and update these useful ANEs. Thanks again!

**Comment by jimmymjing** [comment]
I'm so sorry to bother again! But as my game is going to be published, I just wish to have up to date ANEs... thanks so much!

**Comment by marpies** [comment]
Thanks, we've updated the ANEs.
